version: "3.9"

services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: laravel
        volumes:
            -   .:/var/www
        depends_on:
            - postgres
            - redis
        environment:
            PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
        networks:
            - laravel
        restart: unless-stopped

    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            -   .:/var/www
            -   ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            -   app
        networks:
            - laravel
    postgres:
        image: postgres:14
        container_name: postgres
        restart: always
        environment:
            POSTGRES_DB: aval
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
        ports:
            -   "5432:5432"
        volumes:
            -   pgdata:/var/lib/postgresql/data
        networks:
            - laravel
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@mail.ru
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            -   "5050:80"
        depends_on:
            -   postgres
        networks:
            - laravel
    redis:
        image: redis:alpine
        container_name: redis
        ports:
            -   "6379:6379"
        networks:
            - laravel

volumes:
    pgdata:

networks:
    laravel:
        driver: bridge
